# This workflow installs all GeoCDL dependencies, runs some basic code quality
# checks, and runs all automated tests.
# For more information, see
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions.

name: GeoCDL code checks and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        # Enable dependency caching.
        cache: 'pip'

    - name: Install GDAL
      run: |
        sudo apt-get install -y python3-gdal
        #gdal-config --version
        #gcc --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=84 --statistics

    - name: Run all tests
      run: |
        cd src/tests
        python run_tests.py

